image: node:lts

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  cache:
    paths:
      - node_modules/
  
  before_script:
    - npm ci
  
  script:
    - npm run build-prod
    - cp -a dist/. public/

  artifacts:
    paths:
      - public
